set SOLUTION_NAME=MouseShaker
set SOLUTION_FILE=%SOLUTION_NAME%.sln
set BUILD_CONFIG=Release
set MAIN_PROJECT_OUTDIR=%SOLUTION_NAME%\bin\%BUILD_CONFIG%\net6.0-windows
set ARTIFACTS_BASEDIR=Artifacts
set ARTIFACTS_SUBDIR=%SOLUTION_NAME%
set ARTIFACTS_NAME=%ARTIFACTS_SUBDIR%.zip

dotnet publish --nologo -c %BUILD_CONFIG% -o %ARTIFACTS_BASEDIR%\%ARTIFACTS_SUBDIR% %SOLUTION_FILE% || set ERRORLEVEL=0

del %ARTIFACTS_BASEDIR%\%ARTIFACTS_SUBDIR%\*.pdb

cd %ARTIFACTS_BASEDIR%
7z.exe a -mmt=on -mm=Deflate -mfb=258 -mpass=15 -r ..\%ARTIFACTS_NAME% %ARTIFACTS_SUBDIR%
cd ..
